# Generated by Django 4.2.29 on 2026-04-26 04:31

from django.db import migrations, models
import django.db.models.deletion


def copy_existing_replacement_items(apps, schema_editor):
    Replacement = apps.get_model('core', 'Replacement')
    ReplacementLineItem = apps.get_model('core', 'ReplacementLineItem')

    for replacement in Replacement.objects.all():
        if not replacement.item_name and not replacement.item_description:
            continue
        ReplacementLineItem.objects.create(
            replacement=replacement,
            item_name=replacement.item_name or 'Full Product',
            item_description=replacement.item_description or '',
            quantity=replacement.quantity or 1,
            sort_order=0,
        )


def reverse_existing_replacement_items(apps, schema_editor):
    Replacement = apps.get_model('core', 'Replacement')

    for replacement in Replacement.objects.all():
        first_item = replacement.line_items.order_by('sort_order', 'id').first()
        if not first_item:
            replacement.item_name = ''
            replacement.item_description = ''
            replacement.quantity = 1
        else:
            replacement.item_name = first_item.item_name
            replacement.item_description = first_item.item_description
            replacement.quantity = first_item.quantity
        replacement.save(update_fields=['item_name', 'item_description', 'quantity'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_item_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('part_code', models.CharField(blank=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.replacement')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.RunPython(copy_existing_replacement_items, reverse_existing_replacement_items),
    ]
