# Generated by Django 4.2.29 on 2026-04-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_replacementlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementlineitem',
            name='part_code',
        ),
    ]
