# Generated by Django 4.2.29 on 2026-04-26 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_remove_replacementlineitem_part_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_replacements', to=settings.AUTH_USER_MODEL),
        ),
    ]
