# Generated by Django 4.2.29 on 2026-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_replacement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='new_fan_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='repeated_complaint_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
