# Generated by Django 4.2.29 on 2026-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ticket_issue_notes_ticket_new_fan_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='custom_challan_number',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
