# Generated by Django 4.2.29 on 2026-06-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_savedview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DUPLICATE', 'Duplicate'), ('CUSTOMER_SOLVED', 'Problem Solved at Customer End')], default='OPEN', max_length=20),
        ),
    ]
