# Generated by Codex on 2026-06-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_report_engineer_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='model',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_products', to='core.item')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rows', to='core.ticket')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='ticketproduct',
            constraint=models.UniqueConstraint(fields=('ticket', 'item'), name='unique_ticket_product_item'),
        ),
    ]
