# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ticketproduct_alter_ticket_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproduct',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]